### ISSUE TITLE
Create writeup for section 3

### ISSUE THREAD

**Issue by ph0429** [andersthemagi/ai-scam-detection#10]
writeup for section 3 - https://docs.google.com/document/d/1SCztrhkaBOqpKkgcZsuhX8VfFEKtrqzWrK09s6eIBsg/edit

**Comment by ph0429** [comment]
@andersthemagi creating this task to confirm completion.
Could you share when you expect to write up section 3?

**Comment by andersthemagi** [comment]
At a high level for ideas:

We utilized the OpenAI API in order to handle text and audio processing for this demo. Our website was built using Python and the Streamlit platform to facilitate rapid deployment and to focus on the content of the demo. This was split into different attack vectors, text message, email, and audio, to show various applications of a model towards GuardianAI. We also included a rudimentary "scam education" section to provide insight on what kind of training we could provide users to proactively guide against scams as new methods arise. 

https://ai-scam-detection.streamlit.app/audio

Building a full solution for GuardianAI would require extensive research into which models can faciliate certain workflows, fine-tuning both input and output, and leveraging other API solutions to provide a deeper analysis into the likelihood of a scam with the attack vector provided. Solutions like [Hive.ai](https://docs.thehive.ai/docs/ai-generated-audio-detection) and [Resemble.ai](https://www.resemble.ai/detect/) are likely candidates to handle situations where a transcript alone cannot prove whether it is a scam, ai-generated, etc.

**Comment by andersthemagi** [comment]
We also took the time to iterate over what these ideas would look like to the user, since thankfully we had UI/UX experience on the team. We've included these mockups to show how Guardian AI ***might*** help with user scam prevention in real-time.

**Comment by andersthemagi** [comment]
Updated my first comment to clarify on the structure of the demo

**Comment by andersthemagi** [comment]
@ph0429 would the above work for the writeup? I can add it to the doc in a moment, just thought I'd share my thoughts

**Comment by ph0429** [comment]
@andersthemagi that all works, thanks!
I've added to the doc, minor revisions to keep the doc within page limit.
We should now be done with the content 💪
