### ISSUE TITLE
UI/UX Mockup for Long-Term Solution

### ISSUE THREAD

**Issue by andersthemagi** [andersthemagi/ai-scam-detection#4]
I think in terms of showcasing and "pitching" an idea like this, a mockup of what the UI could look like if we had more resources would be extremely helpful. If Miss Sirpentious would like to take on that, that would be fantastic. 

From what Patrick and I discussed, the app would have multiple "attack vectors" to identify: text, email, and audio. Likely could be a plugin or a standalone web app to input said text. Maybe the user sees notifications while they're on their gmail via a plugin? Maybe they get a notification to their phone while looking at a text? 

The audio bit is a lot harder to model for sure. How do you show in a Figma design that a user is receiving audio and potentially a notification? Maybe a call in-progress with a notification? The document has a lot more context, but honestly that's the beauty of such an open-ended hackathon. We can take creative liberties within reason lol.

_edit: untagged the user that was on this task. Sorry to whoever that was!_

**Comment by andersthemagi** [comment]
@doro14 has this claimed. Patrick will probably be living here in this task as well lol

**Comment by ph0429** [comment]
My initial thoughts on the screens in Figma below.
Note: I am purposely not adding a screen for the app itself at this time. I would like to prioritise the key feature around notifications/alerts as a must-have for the design. If we can complete these screens, then I'm happy to discuss others as a nice-to-have.

SMS:
- Home screen of a user's device. If you would like, you can include a shield as our logo with the app name of Guardian AI. Preference for an Android per https://www.statista.com/forecasts/911113/smartphone-os-share-by-age-group-in-the-us (but if iOS is easier, then feel free to use iOS)
- Home screen of the native Messages app with one unread message in bold. The unread message should have a name like Gov UK with the first line of the message (message text TBD, you can add placeholder text for now)
- Screen for the message. This screen should show a popup over the message text.
Popup:
- text - Guardian AI has flagged this message as a potential scam. Please confirm with the sender before sharing any sensitive details. Note: we have shared this notification with your trusted contact(s).
- a More details at the bottom of this main text for the user to see this text:
We flagged this message because:
- this sender is identified as a scam in [database name]
- this message contains an unknown link that is not associated with the sender. Typically, links should include the name of the organisation or sender, e.g.www.payments.service.gov.uk
- [another reason]
- option at the bottom to confirm or deny the flag eg thumbs up or down.

Email:
- Same home screen of a user's device
- Home screen of Gmail with one unread message in bold. The unread message should have the same as above.
- Same text and option as the popup above.

Voice/Call:
- Same home screen of a user's device
- Screen of Call app with an active call. Use the same Gov UK name and a fake +44 number.
- Same text and option as the popup above.
- I think an option to have Guardian AI to respond to the caller may be relevant. For ex, my device already offers this option: https://support.google.com/phoneapp/answer/9118387?hl=en-GB

**Comment by ph0429** [comment]
@doro041 FYI I'm available until around 9pm UK time in case you're able to share anything by then. 
If not, I'll review tomorrow morning around 10a

**Comment by doro041** [comment]
Hi, I am going to sahre something soon

**Comment by ph0429** [comment]
Thanks for the update @doro041 👍 
Can you share within the next 30 mins or so? I wanted to see what progress you have made and then I can take over from now. My aim is that we have something to show, if only screenshots of the app on the writeup.
That work?

**Comment by doro041** [comment]
Hi, yeah sure - I have used IOS wireframes.

**Comment by ph0429** [comment]
https://www.figma.com/design/gCm2fJaxBt2guJjTlZ9LF5/Untitled?node-id=0-1&node-type=CANVAS&t=7r0mjHIgvfnLPTjA-0

**Comment by ph0429** [comment]
Hey @doro041 - I see this draft, thanks for creating 👍 
I'm happy to take over now

**Comment by ph0429** [comment]
@doro041 FYI I've used your design as a guideline, I've created three screens below and added these as screenshots.

For reference, I used these templates to create the design:
alerts - https://www.figma.com/design/6XRdxCBCLDcnVF8xuq7v02/iOS-Alerts-(Community)?node-id=1-38&node-type=FRAME&t=qUxir5qzMBZoPIJw-0
mail app - https://www.figma.com/design/ogc0Ic2uY6NfoV6ukZpbRz/Mail-App-for-iOS-(Community)?node-id=17-374&node-type=FRAME&t=wsLAzjeekvgnoIH5-0
phone/call app - https://www.figma.com/design/uM3PpLGScwhp9QFb6AFvoT/iOS-Phone-%26-Facetime-Call-UI-(Community)?node-id=1-359&t=VClwN6GFo9HFuctW-0
messages app - https://www.figma.com/design/Lry0HXUu5Lmuz2UvFrStg6/iOS-Message-App--Pin-Conversation--New-Concept-(Community)?node-id=12-2452&node-type=FRAME&t=YdvPvrcjmyd78tD7-0

**Comment by ph0429** [comment]
added to doc https://docs.google.com/document/d/1SCztrhkaBOqpKkgcZsuhX8VfFEKtrqzWrK09s6eIBsg/edit
@andersthemagi FYI
